apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simple-app-deployment
  namespace: development
  labels:
    app: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: docker.io/khairane/simpleapp:1.5
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: my-simple-app-service
  namespace: development
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: NodePort
